# 使用官方Nginx镜像作为基础镜像
FROM nginx:1.28.0-alpine

# 移除默认的Nginx配置文件
RUN rm /etc/nginx/conf.d/default.conf

# 将自定义的Nginx配置文件复制到容器中
COPY nginx.conf /etc/nginx/conf.d/

# 将打包好的Vue3应用文件复制到Nginx的静态文件目录
COPY gzh/ /gzh/

# 暴露容器的8686端口
EXPOSE 8686

# 启动Nginx服务
CMD ["nginx", "-g", "daemon off;"]